# Pipeline for smoke testing other ML packages

trigger: none # No CI build

pr: none # Not for pull requests

pool:
  vmImage: 'ubuntu-latest'

jobs:
- template: templates/other-ml-job-template.yml
  parameters:
    poolImage: ubuntu-latest