# Pipeline for smoke testing other ML packages

trigger: none # No CI build

pr: none # Not for pull requests

schedules:
- cron: "0 8 * * *" # Time is UTC
  displayName: Nightly Build
  branches:
    include:
      - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

jobs:
- template: templates/other-ml-job-template.yml
  parameters:
    poolImage: ubuntu-latest