parameters:
  baseDir: test_othermlpackages
  condaEnv: test-conda-env
  packages: { LightGBM: lightgbm, XGBoost: xgboost }
  poolImage: ubuntu-latest
  pythonVersion: 3.8


jobs:
- ${{ each package in parameters.packages }}:
  - job:
    displayName: "${{ format('Test {0}', package.Key) }}"
    pool:
      vmImage: ${{parameters.poolImage}}
        
    variables:
      condaFile: "${{ format('{0}/conda-{1}.yaml', parameters.baseDir, package.Value) }}"

    steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH for Linux

    - bash: conda env create --name ${{parameters.condaEnv}} --file=$(condaFile)
      displayName: Create Anaconda environment

    - bash: |
        source activate ${{parameters.condaEnv}}
        pip install .
      displayName: Install Fairlearn

    