parameters:
  baseDir: test_othermlpackages
  condaEnv: test-conda-env
  packages: { LightGBM: lightgbm, XGBoost: xgboost }
  poolImage: ubuntu-latest
  pythonVersion: 3.8


jobs:
- ${{ each package in parameters.packages }}:
  - job:
    displayName: "${{ format('Test {0}', package.Key) }}"
    pool:
      vmImage: ${{parameters.poolImage}}
        
    variables:
      condaFile: "${{ format('{0}/conda-{1}.yaml', parameters.baseDir, package.Value) }}"
      testFile: "${{ format('{0}/test_{1}.py', parameters.baseDir, package.Value) }}"

    steps:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH for Linux

    - bash: conda env create --name ${{parameters.condaEnv}} --file=$(condaFile)
      displayName: Create Anaconda environment

    - bash: |
        source activate ${{parameters.condaEnv}}
        pip install .
      displayName: Install Fairlearn

    - bash: |
        source activate ${{parameters.condaEnv}}
        python -m pytest $(testFile) --junitxml=./TEST-TEST.xml -o junit_suite_name="$(Agent.JobName)"
      displayName: Run tests for ${{package.Key}}
    
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/TEST-*.xml'
      condition: succeededOrFailed()
    